CREATE SEQUENCE seq_aluno START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_professor START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_curso START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_disciplina START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_matricula START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_turma START WITH 1 INCREMENT BY 1;